# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eager.proto',
  package='',
  syntax='proto3',
  serialized_options=b'B\nEagerProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65\x61ger.proto\":\n\x07General\x12\x0e\n\x06sender\x18\x01 \x01(\x05\x12\x10\n\x08receiver\x18\x02 \x01(\x05\x12\r\n\x05nodes\x18\x03 \x01(\t\"\x16\n\x04Last\x12\x0e\n\x06leader\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2;\n\x05\x45\x61ger\x12\x1a\n\x04Send\x12\x08.General\x1a\x06.Empty\"\x00\x12\x16\n\x03\x45nd\x12\x05.Last\x1a\x06.Empty\"\x00\x42\x0e\x42\nEagerProtoP\x01\x62\x06proto3'
)




_GENERAL = _descriptor.Descriptor(
  name='General',
  full_name='General',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='General.sender', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='General.receiver', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='General.nodes', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=73,
)


_LAST = _descriptor.Descriptor(
  name='Last',
  full_name='Last',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leader', full_name='Last.leader', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=97,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['General'] = _GENERAL
DESCRIPTOR.message_types_by_name['Last'] = _LAST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

General = _reflection.GeneratedProtocolMessageType('General', (_message.Message,), {
  'DESCRIPTOR' : _GENERAL,
  '__module__' : 'eager_pb2'
  # @@protoc_insertion_point(class_scope:General)
  })
_sym_db.RegisterMessage(General)

Last = _reflection.GeneratedProtocolMessageType('Last', (_message.Message,), {
  'DESCRIPTOR' : _LAST,
  '__module__' : 'eager_pb2'
  # @@protoc_insertion_point(class_scope:Last)
  })
_sym_db.RegisterMessage(Last)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'eager_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_EAGER = _descriptor.ServiceDescriptor(
  name='Eager',
  full_name='Eager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=108,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='Send',
    full_name='Eager.Send',
    index=0,
    containing_service=None,
    input_type=_GENERAL,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='End',
    full_name='Eager.End',
    index=1,
    containing_service=None,
    input_type=_LAST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EAGER)

DESCRIPTOR.services_by_name['Eager'] = _EAGER

# @@protoc_insertion_point(module_scope)
